// http://kotabogor.go.id/index.php/rute

var columns = ['NO RUTE ANGKOT', 'TRAYEK', 'BERANGKAT', 'rute berangkat', 'KEMBALI', 'rute kembali'];
var raw = [
  'AK-01 	CIPINANG GADING – CIPAKU – MERDEKA PP. / 13,83 KM	BERANGKAT 	CIPINANG GADING – CIPAKU – JL.PAHLAWAN – JL.EMPANG – JL.Ir.H.DJUANDA – JL.PALEDANG – JL.KAPTEN MUSLIHAT – JL.VETERAN – JL.PERINTIS KEMERDEKAAN – TERMINAL MERDEKA	KEMBALI 	TERMINAL MERDEKA – JL.Dr.SEMERU – JL.MAWAR – JL. MERDEKA – JL. MA SALMUN – JL.NYI RAJA PERMAS – GG. MESJID – JL.DEWI SARTIKA – JL.KAPTEN MUSLIHAT – JL.Ir.H.DJUANDA – JL.OTISTA – PASAR BOGOR – JL.RODA – GG.AUT – JL.SILIWANGI – JL.BATUTULIS – CIPAKU – CIPINANG GADING',	
  'AK-01-A 	BARANANGSIANG – TAJUR – CIAWI PP. / 8 KM	BERANGKAT 	BARANANGSIANG – JL.BANGKA – JL.OTISTA – PAJAJARAN – JL.TAJUR – CIAWI	KEMBALI 	CIAWI – JL.TAJUR – JL.PAJAJARAN – JL.SAMBU – BARANANGSIANG',
  'AK-02 	SUKASARI – TERMINAL BUBULAK PP. / 14,4 KM	BERANGKAT 	SUKASARI – JL.LAWANG GINTUNG – JL.PAHLAWAN – JL.EMPANG – JL.Ir.H.DJUANDA – JL.PALEDANG – JL.KAPTEN MUSLIHAT – JL.VETERAN – JL.GUNUNG BATU – JL.SINDANG BARANG – JL.SINDANG BARANG PILAR – JL.R.1 – TERMINAL BUBULAK	KEMBALI 	TERMINAL BUBULAK – JL.R-1 – JL.SINDANG BARANG PILAR – JL.SINDANG BARANG – JL.GUNUNG BATU – JL.VETERAN – JL.PERINTIS KEMERDEKAAN – JL.MALL.1 (TERMINAL MERDEKA) – JL.MERDEKA – JL.KAPTEN MUSLIHAT – JL.NYI RAJA PERMAS – GG.MASJID – JL.DEWI SARTIKA – JL.KAPTEN MUSLIHAT – JL.Ir.H.DJUANDA – JL.SURYA KENCANA – JL.SILIWANGI – SUKASARI',
  'AK-03 	BARANANGSIANG – TERMINAL BUBULAK PP. / 11,3 KM	BERANGKAT 	BARANANGSIANG – JL.BANGKA – JL.OTISTA – JL.RAYA PAJAJARAN – JL.JALAK HARUPAT – JL.Ir.H.DJUANDA – JL,KAPTEN MUSLIHAT – JL.VETERAN – JL.GUNUNG BATU – JL.SINDANG BARANG – JL.SINDANG BARANG PILAR – JL.R-1 – TERMINAL BUBULAK	KEMBALI 	TERMINAL BUBULAK – JL.R-1 – JL.SINDANG BARANG PILAR – JL.SINDANG BARANG – JL.GUNUNG BATU – JL.VETERAN – JL.PERINTIS KEMERDEKAAN – JL.MALL.1 (TERMINAL MERDEKA) – JL.MERDEKA – JL.KAPTEN MUSLIHAT – JL.NYI RAJA PERMAS – GG.MASJID – JL.DEWI SARTIKA – GG.MEKAH – JL.GEDONG SAWAH – JL.Ir.H.DJUANDA – JL.JALAK HARUPAT – JL.SALAK – JL.RAYA PAJAJARAN – JL.SAMBU – BARANANGSIANG',	
  'AK-04 	WARUNG NANGKA – RANCAMAYA – RAMAYANA PP. /16 KM	BERANGKAT 	WARUNG NANGKA – RANCAMAYA – DETOUR ROAD / COGREG – JL.CIPAKU – JL.PAHLAWAN – GG.AUT – JL.LAWANG SAKETENG – RAMAYANA	KEMBALI 	RAMAYANA – JL.EMPANG – JL.PAHLAWAN – JL.CIPAKU – DETOUR ROAD / COGREG – RANCAMAYA – WARUNG NANGKA',
  'AK-05 	CIMAHPAR – PANGRANGO – RAMAYANA PP. / 8,9 KM	BERANGKAT 	CIMAHPAR – JL.SANCANG – JL.KUMBANG – JL.LODAYA – JL.PANGRANGO – JL.JALAK HARUPAT – JL.Ir.H.DJUANDA – RAMAYANA	KEMBALI 	RAMAYANA – JL.Ir.H.DJUANDA – JL.OTISTA – JL.PAJAJARAN – JL.LODAYA – JL.SANCANG – CIMAHPAR',
  'AK-06 	CIHEULEUT – JL.BANGKA – RAMAYANA / 11,95 KM	BERANGKAT 	CIHEULEUT – JL.PAJAJARAN – JL.SAMBU – JL.BANGKA – JL.OTISTA – JL.PAJAJARAN – JL.JALAK HARUPAT – JL.Ir.H.DJUANDA – RAMAYANA	KEMBALI 	RAMAYANA – JL.Ir.H.DJUANDA – JL.OTISTA – JL.PAJAJARAN – CIHEULEUT',
  'AK-07 	CIPARIGI – TERMINAL MERDEKA PP. / 14,1 KM	BERANGKAT 	CIPARIGI – JL.RAYA PEMDA KD. HALANG – SIMPANG TALANG – WARUNG JAMBU – JL.JEND.A.YANI – JL.JEND.SUDIRMAN – JL.Ir.H.DJUANDA – JL.KAPTEN MUSLIHAT – JL.VETERAN – JL.PERINTIS KEMERDEKAAN – TERMINAL MERDEKA	KEMBALI 	TERMINAL MERDEKA – JL.Dr.SEMERU – JL.MAWAR – JL. MERDEKA – JL.MA SALMUN – JL.DEWI SARTIKA – PENGADILAN – JL. JEND. SUDIRMAN – JL.PEMUDA – JL.DADALI – WARUNG JAMBU – SIMPANG TALANG – JL. RAYA PEMDA KD. HALANG – CIPARIGI',
  'AK-08 	WR. JAMBU – JL.Ir.H.DJUANDA – RAMAYANA PP. / 7,1 KM	BERANGKAT 	WARUNG JAMBU – JL.PAJAJARAN – JL.PANGRANGO – JL.JALAK HARUPAT – JL.Ir.H.DJUANDA – RAMAYANA	KEMBALI 	RAMAYANA – JL.OTISTA – JL.PAJAJARAN – WARUNG JAMBU',
  'AK-09 	CIPARIGI – SUKASARI PP. / 10,15 KM	BERANGKAT 	CIPARIGI – JL. PEMBANGUNAN (KOPEM) – Jl. KEDUNG HALANG – WARUNG JAMBU – JL.PAJAJARAN – SUKASARI	KEMBALI 	SUKASARI – JL.PAJAJARAN – JL.SAMBU – JL.BANGKA – JL.OTISTA – JL.PAJAJARAN – WARUNG JAMBU – JL. KEDUNG HALANG – JL. PEMBANGUNAN (KOPEM) – CIPARIGI',
  'AK-10 	BANTAR KEMANG – SUKASARI – MERDEKA PP. / 8,75 KM	BERANGKAT 	BANTAR KEMANG – JL.PAJAJARAN – JL.SILIWANGI – JL.LAWANG GINTUNG – JL.PAHLAWAN – JL.EMPANG – JL.Ir.H.DJUANDA – JL.PALEDANG – JL.VETERAN – JL.PERINTIS KEMERDEKAAN – TERMINAL MERDEKA	KEMBALI 	TERMINAL MERDEKA – JL.Dr.SEMERU – JL.MAWAR – JL. MERDEKA – JL. MA SALMUN – JL.NYI RAJA PERMAS – JL.DEWI SARTIKA – GG. MESJID – JL. KAPTEN MUSLIHAT – JL.Ir.H.DJUANDA – JL.SURYAKENCANA – JL.SILIWANGI – SUKASARI I – JL.PAJAJARAN – BANTAR KEMAN',
  'AK-11 	PAJAJARAN INDAH – PASAR BOGOR PP. / 7,3 KM	BERANGKAT 	PAJAJARAN INDAH – JL.PAJAJARAN – JL.SAMBU – JL.BANGKA – JL.OTISTA – PASAR BOGOR	KEMBALI 	PASAR BOGOR – JL.RODA – GG.AUT – JL.SILIWANGI – JL.SUKASARI III – JL.PAJAJARAN – PAJAJARAN INDAH',	
  'AK-12 	CIMANGGU – MA. SALMUN – PASAR ANYAR PP. / 9,8 KM	BERANGKAT 	CIMANGGU PERMAI – JL.CIMANGGU – JL.MERDEKA – JL.MA SALMUN – PASAR ANYAR	KEMBALI 	PASAR ANYAR – JL.PENGADILAN – JL. JEND. SUDIRMAN – JL. RE MARTADINATA – JL.CIMANGGU – CIMANGGU PERMAI',
  'AK-13 	BANTAR KEMANG – JL.BANGKA – RAMAYANA PP. / 7,5 KM	BERANGKAT 	BANTAR KEMANG – JL.RAYA PAJAJARAN – JL.SAMBU – JL.BANGKA – JL.OTISTA – JL.RAYA PAJAJARAN – JL.JALAK HARUPAT – JL.Ir.H.DJUANDA – RAMAYANA	KEMBALI 	RAMAYANA – JL.Ir.H.DJUANDA – JL.OTISTA – JL.RAYA PAJAJARAN – BANTAR KEMANG',
  'AK-14 	SUKASARI – PASIR KUDA – BUBULAK PP. / + 12,65 KM	BERANGKAT 	SUKASARI – JL.LAWANG GINTUNG – JL.PAHLAWAN – JL.LAYUNGSARI – JL.SADANE – JL.R.ARIA SURIAWINATA – JL.R.ARIA SURIALAGA – JL.R.E.ABDULLAH – JL.MAYJEN ISHAK DJUARSA – JL.LETJEN IBRAHIM ADJIE – JL.K.H.ABDULLAH BIN NUH – TERMINAL BUBULAK	KEMBALI 	TERMINAL BUBULAK – JL. K.H.ABDULLAH BIN NUH – JL.LETJEN IBRAHIM ADJIE – JL.MAYJEN ISHAK DJUARSA – JL.R.E.ABDULLAH – JL.R.ARIA SURIALAGA – JL.R.ARIA SURIAWINATA – JL.SADANE – JL.LAYUNGSARI – JL.PAHLAWAN – JL.BATUTULIS – JL.SILIWANGI – SUKASARI',
  'AK-15 	MERDEKA – BUBULAK – SBJ PP. / 6,2 KM	BERANGKAT 	SBJ – TERMINAL BUBULAK – JL. R.1 – JL.SINDANG BARANG – JL.DARUL QUR’AN – JL.DR.SEMERU – JL.MAWAR – JL.MERDEKA – TERMINAL MERDEKA	KEMBALI 	TERMINAL MERDEKA – JL.DR.SEMERU – JL.DARUL QUR’AN – JL.SINDANG BARANG – JL.R.1 – TERMINAL BUBULAK – SBJ',
  'AK-16 	PASAR ANYAR – SELABENDA PP. / 12 KM	BERANGKAT 	PASAR ANYAR – JL.PENGADILAN – JL.JEND.SUDIRMAN – JL.PEMUDA – KEBON PEDES – JL.SOLEH ISKANDAR – SELABENDA	KEMBALI 	SELABENDA – JL.SOLEH ISKANDAR – KEBON PEDES – JL.PEMUDA – JL.HEULANG – JL.JEND.A.YANI – JL.JEND.SUDIRMAN – JL.SAWOJAJAR – JL. DEWI SARTIKA – PASAR ANYAR',
  'AK-17 	POMAD – TANAH BARU – BINA MARGA PP. / 9,2 KM	BERANGKAT 	POMAD – JL.PANGERAN SOGIRI (TANAH BARU) – JL.R.KAN AN (PASAR TANAH BARU) – JL.PANDU RAYA (R3) – JL.PADI – JL.BINA MARGA – BINA MARGA	KEMBALI 	BINA MARGA – JL.BINA MARGA – JL.PADI – JL.PANDU RAYA (R3) – JL.TUMENGGUNG WIRADIRDJA – JL.PANGERAN SOGIRI (TANAH BARU) – POMAD',
  'AK-18 	RAMAYANA – MULYAHARJA PP. / 9 KM	BERANGKAT 	MULYAHARJA – CIBEUREUM – EMPANG – GG.AUT – LAWANG SAKETENG – RAMAYANA	KEMBALI 	RAMAYANA – EMPANG – CIBEUREUM – MULYAHARJA',
  'AK-19 	TERMINAL BUBULAK – KENCANA PP. / 9,5 KM	BERANGKAT 	TERMINAL BUBULAK – JL. R.1 – JL. YASMIN – JL. SOLEH ISKANDAR – JL. KAYUMANIS – JL. MEKAR WANGI – KENCANA	KEMBALI 	KENCANA – JL. MEKARWANGI – KAYUMANIS – JL. SOLEH ISKANDAR – JL. YASMIN – JL. R.1 – TERMINAL BUBULAK',	
  'AK-20 	PASAR ANYAR – KENCANA PP. / 9,5 KM	BERANGKAT 	PASAR ANYAR – JL. KEBON PEDES – JL. SOLEH ISKANDAR – KENCANA	KEMBALI 	KENCANA – JL. SOLEH ISKANDAR – JL. KEBON PEDES – PASAR ANYAR',	
  'AK-21 	Pasar Bogor-Taman Kencana-Ciremai Ujung	BERANGKAT 	Pasar Bogor-Taman Kencana-Ciremai Ujung	KEMBALI 	Ciremai Ujung-Taman Kencana-Pasar Bogor',
  'AK-22 	PASAR ANYAR – PONDOK RUMPUT PP. / 6,9 KM	BERANGKAT 	PONDOK RUMPUT – JL.RE MARTADINATA – AIR MANCUR – JL. JEND. SUDIRMAN – JL.SAWOJAJAR – PASAR ANYAR	KEMBALI 	PASAR ANYAR – JL.PENGADILAN – JL. JEND. SUDIRMAN – AIR MANCUR – JL.RE MARTADINATA – PONDOK RUMPUT',	
  'AK-23 	RAMAYANA – TAMAN KENCANA – WARUNG JAMBU	BERANGKAT 	RAMAYANA – TAMAN KENCANA – WARUNG JAMBU		KEMBALI 	WARUNG JAMBU – TAMAN KENCANA – RAMAYANA'
];

const LINE_NO_COL = 0;
const NAME_COL = 1;
const STOPS_COL = 3;

var lat = {};
var lon = {};
var routes = {};
var indices = Object.keys(raw);
for (var i in indices) {
  var cells = raw[indices[i]].split('\t');
  var lineNo = cells[LINE_NO_COL].trim();
  routes[lineNo] = {
    name: cells[NAME_COL].split('/')[0].trim(),
    stops: []
  };
  var stops = cells[STOPS_COL].split(/[–-]/);
  for (var j=0; j<stops.length; j++) {
    var place = stops[j].toLowerCase().trim();
    lat[place] = -6.6;
    lon[place] = 106.8;
    // console.log([lineNo, lat[place], lon[place], j, j*0.01, place].join(','));
    routes[lineNo].stops.push(place);
  }
}
console.log(JSON.stringify({
  places: Object.keys(lat).sort(),
  routes
}, null, 2));
